project:
  type: website
  render:
    - "*.qmd"
    - "!vignettes/"
    - "!*.Rmd"


website:
  title: ""
  description: art
  #open-graph:
    #image: imgs/things.jpg
  #google-analytics: ""
  navbar:
    #style: "floating"
    #search: false
    left:
      - href: index.qmd
        text: Artworks
      - href: blog.qmd
        text: Substack
      - href: about.qmd
        text: About
  sidebar:
    right:
      contents:
        - about-sidebar.qmd

  page-footer: 
    left: "Copyright [Raphaële Slimane {{< fa brands instagram>}}](https://www.instagram.com/slimaneraphaele/). All rights reserved." 
    right: 
      - icon: instagram
        href: https://www.instagram.com/slimaneraphaele/
  back-to-top-navigation: true
  # navbar:
  #   background: light
  #   search: true
  #   left:
  #     - text: "_Raphaële Slimane's corner_"
  #       href: index.qmd
  #     - text: "{{< fa brands instagram >}}"
  #       href: https://www.instagram.com/slimaneraphaele/
  #   right: 
  #     - text: "{{< fa brands instagram >}}"
  #       href: https://www.instagram.com/slimaneraphaele/

format:
  html:
    theme: 
      light: litera
      dark: slate
    css: 
      - styles/styles.css
    toc: false
    # page-layout: article
    grid:
      sidebar-width: 100px
      body-width: 1000px
      margin-width: 150px

